import type { GameState } from "../types";

export const CONFIG = {
	// Physics
	GRAVITY: 1200,
	JUMP_STRENGTH: -400,
	MAX_FALL_SPEED: 600,
	BASE_SPEED: 250,
	SPEED_INC_PER_EVO: 60,

	// Gameplay
	EVO_THRESHOLD: 100,
	THEME_THRESHOLD: 300,
	MAX_HEARTS: 3,
	INVULNERABLE_DURATION: 1.0,
	FLASH_SPEED: 0.1,
	HIT_FLASH_DURATION: 0.15,

	// Visuals
	CANVAS_WIDTH: 800,
	CANVAS_HEIGHT: 600,
	GAP_SIZE: 150,
	OBSTACLE_WIDTH: 60,
	SPAWN_INTERVAL: 2000,
	INITIAL_SPAWN_DELAY: -4500,

	// Speed Lines
	SPEED_LINE_COUNT: 34,
	SPEED_LINE_MIN_LEN: 40,
	SPEED_LINE_MAX_LEN: 100,
	SPEED_LINE_MIN_SPEED: 800,
	SPEED_LINE_MAX_SPEED: 1500,
	SPEED_LINE_BOOST_OPACITY: 0.48,

	// Powerups
	BONE_BONUS: 50,
	BONE_SPEED_BOOST: 1.5,
	BONE_BOOST_DURATION: 5,
	BONE_SPAWN_MIN: 100,
	BONE_SPAWN_MAX: 250,
	DIAMOND_THRESHOLD: 500,
	MAGNET_THRESHOLD: 400,
	SUPER_TREX_DURATION: 20,
	MAGNET_DURATION: 15,
	POWERUP_RADIUS: 15,
	POWERUP_LARGE_RADIUS: 20,
	POWERUP_SPAWN_PADDING: 100,
	EMERALD_SIZE: 42,
	GRAVITY_FLIP_DURATION: 8,
	GRAVITY_FLIP_BONUS: 50,
	DIRECTION_FLIP_DURATION: 8,
	DIRECTION_FLIP_BONUS: 50,
	DIRECTION_FLIP_TRANSITION: 0.6,
	// Shared spawn slot for gravity flip / direction flip powerups
	FLIP_THRESHOLD: 200,
	FLIP_SPAWN_MIN: 80,
	FLIP_SPAWN_MAX: 200,
	ELEMENTAL_SPAWN_MIN: 120,
	ELEMENTAL_SPAWN_MAX: 260,
	TOXIC_WASTE_DURATION: 12,
	TOXIC_WASTE_BONUS: 50,
	TOXIC_DRIP_INTERVAL: 0.07,
	TOXIC_COLOR_BRIGHT: "#7fff00",
	TOXIC_COLOR_BRIGHT_RGB: "127, 255, 0",
	TOXIC_COLOR_DARK: "#4a8a00",
	BURNING_DURATION: 12,
	BURNING_BONUS: 50,
	BURNING_FLAME_INTERVAL: 0.07,
	BURNING_COLOR_BRIGHT: "#ff6600",
	BURNING_COLOR_BRIGHT_RGB: "255, 102, 0",
	BURNING_COLOR_DARK: "#cc2200",
	BURNING_METEOR_COUNT: 10,
	BURNING_METEOR_SPAWN_INTERVAL: 0.08,
	BURNING_METEOR_SPEED: 320,
	BURNING_METEOR_LIFE: 1.4,
	BURNING_RING_COUNT: 2,
	LIGHTNING_DURATION: 12,
	LIGHTNING_BONUS: 50,
	LIGHTNING_COLOR_BRIGHT: "#ffff00",
	LIGHTNING_COLOR_BRIGHT_RGB: "255, 255, 0",
	LIGHTNING_COLOR_ACCENT: "#ffffff",
	LIGHTNING_BOLT_DURATION: 0.35,
	LIGHTNING_SPARK_INTERVAL: 0.08,

	// Coins
	COIN_RADIUS: 12,
	COIN_SPAWN_PROB: 0.015,
	COIN_SPAWN_PROB_MEGA: 0.08,
	COIN_DNA_PADDING: 15,
	COIN_PARTICLE_COLOR: "#ffd700",
	MAGNET_SPEED: 600,

	// Obstacles
	OBSTACLE_MIN_HEIGHT: 50,
	OBSTACLE_DNA_PADDING: 20,

	// Combo System
	COMBO_TIMEOUT: 2.0,
	COMBO_STAGES: [
		{
			threshold: 5,
			multiplier: 1.5,
			name: "Nice!",
			class: "combo-stage-1",
			color: "#4ade80",
			shake: 2,
		},
		{
			threshold: 10,
			multiplier: 2.0,
			name: "Great!",
			class: "combo-stage-2",
			color: "#fb923c",
			shake: 4,
		},
		{
			threshold: 20,
			multiplier: 3.0,
			name: "Amazing!",
			class: "combo-stage-3",
			color: "#f87171",
			shake: 6,
		},
		{
			threshold: 50,
			multiplier: 5.0,
			name: "Pre-historic!",
			class: "pre-historic",
			color: "#ec4899",
			shake: 10,
		},
	],

	// Screen Shake
	SHAKE_DURATION: 0.2,
	SHAKE_INTENSITY: 5,

	// Effects
	PARTICLE_GRAVITY: 400,
	TRAIL_LIFETIME: 0.3,
	FCT_LIFETIME: 1.0,
	FCT_GRAVITY: 150,
	FCT_INITIAL_VY: -100,
	GLITCH_PERIOD: 0.8,
	GLITCH_BURST_DURATION: 0.08,
	SHOCKWAVE_LIFETIME: 0.36,
	AMBIENT_MOTE_COUNT: 36,
	AMBIENT_MOTE_SPEED: 18,

	// Dino
	DINO_START_X: 50,
	DINO_HITBOX_FACTOR: 0.8,
	DINO_ROTATION_FACTOR: 0.0015,
	DINO_MAX_ROTATION: Math.PI / 4,
	DINO_HISTORY_MAX: 15,
	DINO_BACKFLIP_DURATION: 0.5,
	DINO_FOLLOWER_X: 10,
	DINO_SQUASH_RECOVERY: 10,

	// Scoring
	SUPER_SMASH_SCORE: 10,
	FCT_OFFSET_X: 20,
	FCT_OFFSET_Y: -20,

	// Themes
	THEMES: ["theme-1", "theme-2", "theme-3", "theme-4", "theme-5"],

	// Ground Plane (Mode 7)
	HORIZON_Y: 460,
	GROUND_COLOR_DARK: [45, 35, 25],
	GROUND_COLOR_LIGHT: [75, 60, 45],

	// Day/Night Cycle
	CYCLE_DURATION: 60, // seconds per full cycle
	SKY_COLORS: [
		[10, 10, 20], // Night
		[255, 100, 100], // Dawn
		[100, 200, 255], // Day
		[255, 150, 50], // Dusk
	],

	// Colors
	DINO_COLORS: ["#4ade80", "#fb923c", "#f87171", "#000000"],
	DNA_COLORS: ["#f472b6", "#c084fc", "#818cf8", "#2dd4bf"],

	// Meteor Shower
	METEOR_FIRST_TRIGGER: 250,
	METEOR_INTERVAL_MIN: 800,
	METEOR_INTERVAL_MAX: 1200,
	METEOR_EVENT_DURATION: 3.5,
	METEOR_DARKEN_TIME: 0.5,
	METEOR_ACTIVE_TIME: 2.2,
	METEOR_FADE_TIME: 0.8,
	METEOR_COUNT: 6,
	METEOR_SPAWN_INTERVAL: 0.35,
	METEOR_SPEED_MIN: 350,
	METEOR_SPEED_MAX: 550,
	METEOR_TRAIL_RATE: 60,
	METEOR_TRAIL_LIFE: 0.4,
	METEOR_TRAIL_SPREAD: 15,
	METEOR_IMPACT_RADIUS: 40,
	METEOR_IMPACT_LIFE: 0.6,
	METEOR_SKY_DARKEN_ALPHA: 0.35,
	METEOR_SHAKE_INTENSITY: 3,
	METEOR_COLORS: ["#ff6600", "#ff9933", "#ffcc00", "#ff3300", "#ffaa00"],

	// Quetzalcoatlus Ride
	QUETZ_DURATION: 10,
	QUETZ_THRESHOLD: 400,
	QUETZ_SPAWN_INTERVAL: 300,
	QUETZ_STEER_SPEED: 400,
	QUETZ_LOOK_AHEAD: 300,
	QUETZ_COIN_WEIGHT: 1.0,
	QUETZ_AVOID_WEIGHT: 2.0,
	QUETZ_SAFE_MARGIN: 30,
	QUETZ_WING_FLAP_INTERVAL: 0.4,
	QUETZ_TRAIL_RATE: 0.03,
	QUETZ_SPRITE_SIZE: 250,
	QUETZ_BOB_AMPLITUDE: 8,
	QUETZ_BOB_FREQUENCY: 3,
	QUETZ_ENTER_DURATION: 0.8,
	QUETZ_EXIT_DURATION: 0.8,
	QUETZ_FEATHER_SIZE: 50,

	// Pterodactyl Flock (Background)
	FLOCK_MIN_INTERVAL: 15,
	FLOCK_MAX_INTERVAL: 35,
	FLOCK_SIZE_MIN: 3,
	FLOCK_SIZE_MAX: 7,
	FLOCK_SPRITE_SIZE: 20,
	FLOCK_SPEED_MIN: 60,
	FLOCK_SPEED_MAX: 100,
	FLOCK_Y_MIN: 200,
	FLOCK_Y_MAX: 380,
	FLOCK_SPREAD_X: 40,
	FLOCK_SPREAD_Y: 25,
	FLOCK_WING_FLAP_SPEED: 0.3,
	FLOCK_WAVE_AMPLITUDE: 3,
	FLOCK_WAVE_FREQUENCY: 0.5,

	// Background Sun
	SUN_X: 600,
	SUN_Y: 330,
	SUN_CORE_RADIUS: 120,
	SUN_GLOW_RADIUS: 300,
};

export const GAME_STATE: Record<GameState, GameState> = {
	START: "START",
	PLAYING: "PLAYING",
	PAUSED: "PAUSED",
	GAME_OVER: "GAME_OVER",
};
